### ISSUE TITLE
Add a PR template

### ISSUE THREAD

**Issue by Daksh777** [PatternHouse/Python-PatternHouse#869]
Since there are inconsistencies in the code, for example, either the output is not written or the explanation is not written.
To address this, we can add a PR template with checkboxes/tasks and ensure that the code is consistent.

**Comment by Daksh777** [comment]
Can you assign this issue to me? @aryashah2k

**Comment by aryashah2k** [comment]
Hi there, so there are other plans that we are thinking of in terms of code quality improvement and since there has been a lot of contribution done already, I feel the PR template loses its purpose at this point. I'm afraid I wont be assigning this issue. 
You can in the meanwhile work for the patterns or website improvements if need be :) Hope you can understand the situation!
